Set Shell "FISH_PROMPT=min /usr/bin/fish -PC 'cd ~/'"
Set FontSize 24
Set Width 850
Set Height 500
Set Theme "Gruvbox Dark"
Set Padding 10
Set TypingSpeed 150ms

Type "too" Sleep 500ms Tab
Sleep 1s
Type "e" Sleep 500ms Tab
Sleep 1s
Type "-" Sleep 200ms Tab Sleep 200ms Tab Sleep 200ms Enter
Sleep 500ms
Type "my-lib" Sleep 500ms Enter
Sleep 1s
Type "ggVG" Sleep 50ms Type "d"
Sleep 500ms
Type "Isay_hello() {}ii" Sleep 100ms Type "i" Enter Type `iiOecho "Hello $1"ii` Sleep 3s Type ":wq" Sleep 200ms Enter
Sleep 1s
